### ISSUE TITLE
syncmedia command fails with checkout from master/head

### ISSUE THREAD

**Issue by sbma44** [sunlightlabs/django-mediasync#11]
I just checked out master & installed it, but unfortunately I get this:

my-macbook:project_dir $ ./manage.py syncmedia
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_manager(settings)
  File "/Library/Python/2.5/site-packages/django/core/management/**init**.py", line 362, in execute_manager
    utility.execute()
  File "/Library/Python/2.5/site-packages/django/core/management/**init**.py", line 303, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.5/site-packages/django/core/management/base.py", line 195, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/Library/Python/2.5/site-packages/django/core/management/base.py", line 222, in execute
    output = self.handle(_args, *_options)
  File "/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/mediasync/management/commands/syncmedia.py", line 14, in handle
    mediasync.sync(bucket, prefix.strip('/'))
TypeError: sync() takes at most 1 argument (2 given)

Sure enough, it looks like the signature for the sync() function doesn't match what's getting called from the command:

**init**.py:def sync(client=None):

Not sure how to assemble the client object, but if you can fill me in I'd be happy to put together a patch.

**Comment by jcarbaugh** [comment]
Management command works again.
