### ISSUE TITLE
No matter the settings, getting "No such file or directory" on AWS error

### ISSUE THREAD

**Issue by ghost** [sunlightlabs/django-mediasync#32]
I'm getting a new error when I try to run syncmedia. All of a sudden, mediasync can't see the directory on AWS even though it's making the directories and has started writing files. Here is the traceback that I'm getting:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/home/XXXXXXX/.virtualenvs/cbirt/lib/python2.6/site-packages/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/home/XXXXXXX/.virtualenvs/cbirt/lib/python2.6/site-packages/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/XXXXXXX/.virtualenvs/cbirt/lib/python2.6/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/XXXXXXX/.virtualenvs/cbirt/lib/python2.6/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(_args, *_options)
  File "/home/XXXXXXX/.virtualenvs/cbirt/src/mediasync/mediasync/management/commands/syncmedia.py", line 24, in handle
    mediasync.sync(force=force)
  File "/home/XXXXXXX/.virtualenvs/cbirt/src/mediasync/mediasync/**init**.py", line 147, in sync
    for dirname in os.listdir(client.media_root):
OSError: [Errno 2] No such file or directory: 'http://s3.amazonaws.com/cbirtstagingv3/static_008/'

**Comment by jcarbaugh** [comment]
Hey there,

Sorry, I completely missed this issue. I'm not getting the emails for new issues so I need to look into getting that fixed.

Are you still having this problem?

Jeremy
